prerun: |
  mkdir -p ~/.vscode
  mkdir -p ~/.local/share/ulauncher

copr:
  - pgdev/ghostty
  - troycurtisjr/ulauncher

dnf:
  - zip
  - pipx
  - mako
  - code
  - aria2
  - wtype
  - waybar
  - ghostty
  - nautilus
  - swayidle
  - ulauncher
  - mate-polkit
  - wl-clipboard
  - brightnessctl
  - "gtk-layer-shell" # required for ulauncher
  - "gtk4-layer-shell" # required for niriswitcher
  - NetworkManager-tui

nix:
  - eza
  - dex
  - emote
  - zellij
  - bluetui
  - librewolf

bun: []

flatpak:
  - page.codeberg.libre_menu_editor.LibreMenuEditor
  - io.gitlab.adhami3310.Footage

local:
  niri: |
    sudo dnf install -y \
      gcc clang cargo dbus-devel \
      systemd-devel wayland-devel \
      pipewire-devel libinput-devel \
      pango-devel mesa-libgbm-devel \
      libseat-devel libdisplay-info-devel \
      libxkbcommon-devel cairo-gobject-devel
    cargo build --release
    sudo cp -f target/release/niri /usr/bin/
    sudo cp -f resources/niri-session /usr/bin/
    sudo cp -f resources/niri.desktop /usr/share/wayland-sessions/
    sudo cp -f resources/niri-portals.conf /usr/share/xdg-desktop-portal/
    sudo cp -f resources/niri.service /etc/systemd/user/
    sudo cp -f resources/niri-shutdown.target /etc/systemd/user/
  vivaldi-snapshot: "./install"
  vs-code: "./install"
  niriswitcher: "./install"

symlinks:
  - ["zsh/zshrc", "../.zshrc"]
  - ["mako", "mako"]
  - ["sway", "sway"]
  - ["niri", "niri"]
  - ["niriswitcher", "niriswitcher"]
  - ["ghostty", "ghostty"]
  - ["helix", "helix"]
  - ["waybar", "waybar"]
  - ["ulauncher", "ulauncher"]
  - ["zellij", "zellij"]
  - ["ulauncher/extensions", "../.local/share/ulauncher/extensions"]
  - ["ulauncher/bookmarks", "ulauncher-bookmarks"]
  - ["ulauncher/snippets", "ulauncher-text-snippets"]
  - ["vscode/argv.json", "../.vscode/argv.json"]
  - ["../assets/icons", "../.icons"]
  - ["../assets/themes", "../.themes"]
  - ["../assets/themes/$GTK_THEME/gtk-4.0", "gtk-4.0"]

templates:
  - mako/config.njk
  - ghostty/config.njk
  - niri/config.kdl.njk
  - waybar/config.jsonc.njk
  - niriswitcher/config.toml.njk
  - zellij/config.kdl.njk
  - ulauncher/user-themes/wal/theme.css.njk
  - ulauncher/user-themes/wal/manifest.json.njk

less:
  - waybar/style.less
  - vivaldi-css/style.less
  - niriswitcher/style.less

pm2:
  mako: "mako"
  waybar: "waybar"
  niriswitcher: "~/.local/bin/niriswitcher"
  ulauncher: "ulauncher --daemon"
  niri-disaplay-manager: "{{bin}}/niri-display-manager"
  swaybg-wallpaper: "{{bin}}/swaybg.x64 -n wallpaper  -i {{assets}}/wallpaper.jpg"
  swaybg-overview: "{{bin}}/swaybg.x64 -n overview -i {{assets}}/wallpaper-overview.jpg"
  swayidle: |
    swayidle -w
      timeout 300 'niri msg action power-off-monitors'
      timeout 1800 'systemctl suspend'
  polkit: "/usr/libexec/polkit-mate-authentication-agent-1"

xdg:
  default_browser: vivaldi-snapshot.desktop

system_theme:
  color_scheme: prefer-dark
  accent_color: pink
  gtk_theme: Catppuccin-Macchiato
  icon_theme: Yaru-magenta-dark
  cursor_theme: Yaru
  font_family: Fira Sans
  font_family_mono: Fira Mono

application_theme:
  colors:
    background: "#282a36"
    text: "#f8f8f2"
    primary: "#a4ffff"
    secondary: "#69ff94"
    accent: "#e06c75"
  niri:
    cursor_size: 24
    layout_gaps: 16
    layout_margin_x: 18
    layout_focus_ring_width: 1
    layout_focus_ring_color_start: "{{ colors.accent }}"
    layout_focus_ring_color_end: "#BD93F9"
    layout_border_width: 2
    layout_border_color_start: "{{ colors.secondary }}88"
    layout_border_color_end: "#BD93F988"
    window_corner_radius: 12
  niriswitcher:
    font_family: "{{ fonts.mono }}"
    font_size: 14
    border_radius: 8
    border_width: 2
  ulauncher:
    font_family: "{{ fonts.mono }}"
    border_radius: 8
    border_width: 2
  vivaldi:
    background: "{{ colors.background | darken(0.6) }}"
    accent: "{{ colors.accent }}"
    highlight: "{{ colors.primary | desaturate(0.8) | darken(0.4) }}"
    surface_radius: 8
  mako:
    font_size: 13
    border_size: 2
    border_radius: 8
    border_color: "{{ colors.secondary }}"
  waybar:
    font_size: 13
    laptop_font_size: 14
  ghostty:
    font_size: 12
    background_opacity: 0.95
  zellij:
    theme: catppuccin-mocha
