#!/bin/bash

ROOT=$(dirname "$(realpath "$0")")
GTK_THEME=$(cat $ROOT/niri/config.kdl | grep -oP 'GTK_THEME\s*"\K[^"]+')
source "$ROOT/install.pre"
source "$ROOT/env"

# Setup symlinks
symlink "./easystroke" ".easystroke"
symlink "./paru" ".config/paru"
symlink "./nvim" ".config/nvim"
symlink "./kitty" ".config/kitty"
symlink "./mako" ".config/mako"
symlink "./niri" ".config/niri"
symlink "./ulauncher" ".config/ulauncher"
symlink "./waybar" ".config/waybar"
symlink "./zsh/.zshrc" ".zshrc"
symlink "./gtk/icons" ".icons"
symlink "./gtk/themes" ".themes"
symlink "./gtk/themes/$GTK_THEME/gtk-4.0" ".config/gtk-4.0"

# Install pacman packages
sudo pacman -Sy --needed \
    aria2 wget polkit-gnome zip brightnessctl \
    kitty swaybg mako waybar xwayland-satellite niri \
    wtype wl-clipboard slurp grim gnome-tweaks \
    flatpak zsh nodejs npm jq bluetui spotifyd

# Install aur packages
$AUR_HELPER -Sy --needed \
    ulauncher-git \
    visual-studio-code-bin \
    appimagelauncher \
    easystroke

# Install flatpak apps
flatpak install flathub \
    com.tomjwatson.Emote com.github.tchx84.Flatseal \
    io.github.ungoogled_software.ungoogled_chromium \
    io.gitlab.librewolf-community \
    page.codeberg.libre_menu_editor.LibreMenuEditor

# Setup npm to use local directory
mkdir -p ~/.npm-global
npm config set prefix "~/.npm-global/"

# Install global npm packages
npm install -g yarn less mustache

# Flatpak overrides for themes and icons
sudo flatpak override --filesystem=$HOME/.themes
sudo flatpak override --filesystem=$HOME/.icons
sudo flatpak override --filesystem=xdg-config/gtk-4.0
flatpak override --user --filesystem=xdg-config/gtk-4.0

# Install oh-my-zsh if not already installed
if [ ! -d "$HOME/.oh-my-zsh" ]; then
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi
