#!/usr/bin/env bash
set -Eeuo pipefail

ROOT=$(dirname "$(realpath -P "$0")")

REQUIRED_DNF_PKGS="jq curl zsh helix git dnf-plugins-core nodejs flatpak"
REQUIRED_NIX_PKGS="bun"
REQUIRED_BUN_PKGS="hjson pm2"

# Check if the script is run as root
sudo echo "Starting installation..."

# Load the install-utils script
source "$ROOT/bin/install-utils"

# Link the config directory
rm -f "$HOME/.visualglitch91"
ln -s "$ROOT" "$HOME/.visualglitch91"

# Add bun to the current PATH
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.bun/bin:$PATH"

# Install lix (nix package manager)
if ! command -v nix &>/dev/null; then
  echo "Installing nix package manager"
  sudo setenforce 0
  sh -c "curl -sSf -L https://install.lix.systems/lix | sh -s -- install" >/dev/null 2>&1
  source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
  sudo setenforce 1
fi

install_dnf_packages $REQUIRED_DNF_PKGS
install_nix_packages $REQUIRED_NIX_PKGS
install_bun_packages $REQUIRED_BUN_PKGS

# Install oh-my-zsh (do not fail if already installed or on error)
if [ ! -d "$HOME/.oh-my-zsh" ]; then
  echo "Installing oh-my-zsh"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" >/dev/null 2>&1 || true
fi

# Load the config file
CONFIG=$(hjson -j "$ROOT/config.hjson")
conf() { jq -r ".$1" <<<"$CONFIG"; }

enable_copr_repos $(conf copr[])
install_dnf_packages $(conf dnf[])
install_bun_packages $(conf bun[])
install_nix_packages $(conf nix[])
install_flatpak_packages $(conf flatpak[])

# Install the bin/node_modules
echo "Installing bin/node_modules"
sh -c "cd $ROOT/bin && bun install" >/dev/null 2>&1

# Remove nano, vim, vi in favor of hx
echo "Removing nano, vim, vi in favor of hx"
sudo dnf remove nano -y >/dev/null 2>&1
sudo rm -f /usr/bin/vim
sudo rm -f /usr/bin/nano
sudo rm -f /usr/bin/nvim
sudo ln -s /usr/bin/hx /usr/bin/vim
sudo ln -s /usr/bin/hx /usr/bin/nano
sudo ln -s /usr/bin/hx /usr/bin/nvim

# Make flatpak apps use the local themes
echo "Making flatpak apps use the local themes"
sudo flatpak override --filesystem=$HOME/.themes
sudo flatpak override --filesystem=$HOME/.icons
sudo flatpak override --filesystem=xdg-config/gtk-4.0
flatpak override --user --filesystem=xdg-config/gtk-4.0

# Set theme vars
COLOR_SCHEME=$(conf system_theme.color_scheme)
GTK_THEME=$(conf system_theme.gtk_theme)
ICON_THEME=$(conf system_theme.icon_theme)
CURSOR_THEME=$(conf system_theme.cursor_theme)
ACCENT_COLOR=$(conf system_theme.accent_color)
FONT_FAMILY=$(conf system_theme.font_family)
FONT_FAMILY_MONO=$(conf system_theme.font_family_mono)

# Set the GTK theme, icon theme, cursor theme, and font
echo "Setting the GTK theme, icon theme, cursor theme, and font"
gsettings set org.gnome.desktop.interface color-scheme "$COLOR_SCHEME"
gsettings set org.gnome.desktop.interface gtk-theme "$GTK_THEME"
gsettings set org.gnome.desktop.interface icon-theme "$ICON_THEME"
gsettings set org.gnome.desktop.interface cursor-theme "$CURSOR_THEME"
gsettings set org.gnome.desktop.interface accent-color "$ACCENT_COLOR"
gsettings set org.gnome.desktop.interface font-name "$FONT_FAMILY 11"
gsettings set org.gnome.desktop.interface document-font-name "$FONT_FAMILY 11"
gsettings set org.gnome.desktop.interface monospace-font-name "$FONT_FAMILY_MONO 11"
gsettings set org.gnome.desktop.wm.preferences titlebar-font "$FONT_FAMILY 11"

# Hide the titlebar buttons
gsettings set org.gnome.desktop.wm.preferences button-layout ':'

# Create symlinks
echo $CONFIG | jq -c '.symlinks[]' | while read -r pair; do
  src=$(eval echo "$(echo "$pair" | jq -r '.[0]')")
  dest=$(echo "$pair" | jq -r '.[1]')
  symlink "$src" "$dest"
done

# Init git submodules
echo "Initializing git submodules"
git submodule update --init --recursive >/dev/null 2>&1

# Reload environment
echo "Reloading environment"
$ROOT/scripts/reload >/dev/null 2>&1

# Set the default web browser
DEFAULT_BROWSER=$(echo $CONFIG | jq -r '.xdg.default_browser')
echo "*****************************************"
echo "Run the following command to set the default web browser:"
echo "xdg-settings set default-web-browser $DEFAULT_BROWSER"
