add_newline = false

format = """
$username\
[@$hostname›](purple) \
$directory\
$git_branch\
$git_commit\
$git_status\
$line_break\
$character"""

[directory]
truncation_length = 2
truncate_to_repo = false
style = "blue bold"

[username]
style_root = "red"
style_user = "purple"
show_always = true
format = "[‹$user]($style)"

[hostname]
ssh_only = false
format = '$hostname'

[character]
success_symbol = "[➜](green)"
error_symbol = "[➜](red)"
vimcmd_symbol = "[➜](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"
only_attached = true

[git_commit]
format = "[\\($hash\\)]($style)"
style = "bright-black"
only_detached = true

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"
use_git_executable = true
