export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="risto"

plugins=(
    asdf
    git
)

source $ZSH/oh-my-zsh.sh

# Only source the Cargo environment file if it exists
if [ -f "$HOME/.cargo/env" ]; then
    source "$HOME/.cargo/env"
fi

unsetopt PROMPT_SP

alias open=xdg-open
alias zsh-reload="source ~/.zshrc"

# DNF shortcuts
alias dnfup="sudo dnf update -y"
alias dnfadd="sudo dnf -y install"
alias dnfdel="sudo dnf -y remove"

# Flatpak shortcuts
alias flatadd='flatpak install -y flathub'
alias flatdel='flatpak remove -y'

alias compose="docker compose"
alias nrun="npm run"

alias gl='git pull'
alias gp='git push'
alias gpo='git push -u origin'
alias gs='git status'
alias gb='git branch'
alias gco='git checkout'
alias gcb='git checkout -b'
alias gd='git diff'
alias ga='git add'
alias gall='git add .'
alias gc='git commit'
alias gcm='git commit -m'
alias gcan='git commit --amend --no-edit'
alias git-confia="git add . && git commit --amend --no-edit && git push --force"
alias git-curr-branch='git rev-parse --abbrev-ref HEAD'
alias git-push='git push -u origin $(git-curr-branch)'

export ELECTRON_OZONE_PLATFORM_HINT=wayland

export PATH="$HOME/.npm-global/bin/:$PATH"
export PATH="$HOME/.visualglitch91/scripts/:$PATH"
export PATH="$HOME/.local/bin/:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"

export VISUAL=hx
export EDITOR="$VISUAL"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion

function current_dir() {
    local current_dir=$PWD
    if [[ $current_dir == $HOME ]]; then
        current_dir="~"
    else
        current_dir=${current_dir##*/}
    fi

    echo $current_dir
}

function change_tab_title() {
    local title=$1
    command nohup zellij action rename-tab $title >/dev/null 2>&1
}

function set_tab_to_working_dir() {
    local result=$?
    local title=$(current_dir)
    # uncomment the following to show the exit code after a failed command
    # if [[ $result -gt 0 ]]; then
    #     title="$title [$result]"
    # fi

    change_tab_title $title
}

function set_tab_to_command_line() {
    local cmdline=$1
    change_tab_title $cmdline
}

if [[ -n $ZELLIJ ]]; then
    add-zsh-hook precmd set_tab_to_working_dir
    add-zsh-hook preexec set_tab_to_command_line
fi
