#!/bin/bash

sudo dnf install -y \
  gcc clang cargo dbus-devel \
  systemd-devel wayland-devel \
  pipewire-devel libinput-devel \
  pango-devel mesa-libgbm-devel \
  libseat-devel libdisplay-info-devel \
  libxkbcommon-devel cairo-gobject-devel

cd src
cargo build --release

sudo cp -f target/release/niri /usr/bin/
sudo cp -f resources/niri-session /usr/bin/
sudo cp -f resources/niri.desktop /usr/share/wayland-sessions/
sudo cp -f resources/niri-portals.conf /usr/share/xdg-desktop-portal/
sudo cp -f resources/niri.service /etc/systemd/user/
sudo cp -f resources/niri-shutdown.target /etc/systemd/user/
