#!/bin/bash
source "$HOME/.visualglitch91/env"

RESPONSE=$(
    curl -s -X GET "$HASS_HOST/api/states/$HASS_SPOTIFY_ENTITY" \
        -H "Authorization: Bearer $HASS_TOKEN" \
        -H "Content-Type: application/json"
)

TITLE=$(echo "$RESPONSE" | jq -r '.attributes.media_title // ""')
ARTIST=$(echo "$RESPONSE" | jq -r '.attributes.media_artist // ""')

# Check if both title and artist are present
if [[ -n "$TITLE" && -n "$ARTIST" ]]; then
    SONG="$TITLE - $ARTIST"
else
    exit 0
fi

STATUS=$(echo "$RESPONSE" | jq -r '.state')

# Corrected if statement for comparison
if [[ "$STATUS" == "playing" ]]; then
    echo " $SONG"
    exit
fi

echo " $SONG"
exit
