#!/bin/bash

set -e

DEST_DIR="$HOME/.visualglitch91"
ROOT="$DEST_DIR/config/wallpaper.jpg"
OVERVIEW="$DEST_DIR/config/wallpaper-overview.jpg"

input="$1"

mkdir -p "$DEST_DIR/config"

# If input is a URL
if [[ "$input" =~ ^https?:// ]]; then
    tmpfile=$(mktemp --suffix=.download)
    wget -qO "$tmpfile" "$input"
    input="$tmpfile"
fi

# Convert to jpg if not already
file_ext="${input##*.}"
if [[ "${file_ext,,}" != "jpg" && "${file_ext,,}" != "jpeg" ]]; then
    convert "$input" "$ROOT"
else
    cp "$input" "$ROOT"
fi

# Generate blurred overview image
convert "$ROOT" -blur 0x8 "$OVERVIEW"

pm2 restart visualglitch-os--swaybg
pm2 restart visualglitch-os--swww
